package com.medical.labservice.dto;

import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Data
public class CreateLabResultDTO {

    // There is no filePath here on purpose. It used to be accepted from the
    // request body and written straight to the row, which let a caller point a
    // result at any file already under the storage root. A file arrives through
    // the upload endpoint and its key is generated by the server, never sent.


    @NotNull(message = "Lab Request ID is required")
    private Long labRequestId;

    private String resultText;

    private String observations;
}
