package com.medical.labservice.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Entity
@Table(name = "lab_results")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LabResult {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private Long labRequestId;

    @Column(columnDefinition = "TEXT")
    private String resultText;

    /**
     * Storage key of the attached report, relative to the storage root.
     *
     * Generated by LabFileStore from a UUID; nothing the uploader sent ever
     * appears in it. Null when the result is text only.
     */
    @Column(name = "file_path")
    private String filePath;

    /** The uploader's filename, sanitised. A label and a download name only. */
    @Column(name = "file_name", length = 160)
    private String fileName;

    /** The type the bytes actually are, not the type the upload claimed. */
    @Column(name = "file_content_type", length = 80)
    private String fileContentType;

    @Column(name = "file_size")
    private Long fileSize;

    /** SHA-256 of the stored bytes, so later corruption is detectable. */
    @Column(name = "file_checksum", length = 64)
    private String fileChecksum;

    @Column(name = "file_uploaded_at")
    private LocalDateTime fileUploadedAt;

    /** Whether a report is attached to this result. */
    @Transient
    public boolean hasFile() {
        return filePath != null && !filePath.isBlank();
    }

    private String observations;

    @Column(nullable = false)
    private LocalDateTime resultedAt;

    @PrePersist
    protected void onCreate() {
        this.resultedAt = LocalDateTime.now();
    }
}
